I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/story/secondDayMorning.rpy", line 524, in script
    with Fade(1.5)
TypeError: Fade() takes at least 3 arguments (3 given)

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/story/secondDayMorning.rpy", line 524, in script
    with Fade(1.5)
  File "renpy/ast.py", line 1363, in execute
    renpy.exports.with_statement(trans, paired=paired)
  File "renpy/exports.py", line 1781, in with_statement
    return renpy.game.interface.do_with(trans, paired, clear=clear)
  File "renpy/display/core.py", line 1551, in do_with
    clear=clear)
  File "renpy/display/core.py", line 2165, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, pause=pause, pause_start=pause_start, pause_modal=pause_modal, **kwargs) # type: ignore
  File "renpy/display/core.py", line 2604, in interact_core
    trans = instantiate_transition(None, old_root, layers_root)
  File "renpy/display/core.py", line 2520, in instantiate_transition
    new_widget=new_d)
TypeError: Fade() takes at least 3 arguments (3 given)

Windows-10-10.0.19041 AMD64
Ren'Py 7.7.0.24012702
Sixth hood 1.0
Sun Feb 11 20:38:06 2024
